version: '3.8'

services:
    oms-auth-db:
      image: postgres:14.4-alpine
      container_name: oms-auth-db
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: auth-service
        POSTGRES_PASSWORD: auth-service
        POSTGRES_DB: auth-service
      volumes:
        - ./AuthService/migrations:/docker-entrypoint-initdb.d